function Hd = BP_CHEBY2
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 12-Nov-2023 14:54:30

Fstop1 = 125;    % First Stopband Frequency
Fpass1 = 250;    % First Passband Frequency
Fpass2 = 2000;   % Second Passband Frequency
Fstop2 = 4000;   % Second Stopband Frequency
Astop1 = 60;     % First Stopband Attenuation (dB)
Apass  = 1;      % Passband Ripple (dB)
Astop2 = 60;     % Second Stopband Attenuation (dB)
Fs     = 44100;  % Sampling Frequency

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);

Hd = design(h, 'cheby2', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);


