function Hd = HP_IIR_CHEBY2
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 12-Nov-2023 16:42:05

Fstop = 1000;   % Stopband Frequency
Fpass = 2000;   % Passband Frequency
Astop = 60;     % Stopband Attenuation (dB)
Apass = 1;      % Passband Ripple (dB)
Fs    = 44100;  % Sampling Frequency

h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);

Hd = design(h, 'cheby2', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);


